addons:
  apt:
    packages:
    - python-numpy
install:
  - pip install flake8  # Not yet available in Ubuntu precise (https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise)
  - pip install -e .
language: python
python: "2.7"
script: make test
sudo: false
virtualenv:
  system_site_packages: true
