sudo: false # Use new Travis container-based infrastructure
language: python
python: 2.7
cache: pip
install:
  - pip install --upgrade pip wheel  # pip >= 8.0 needed to be compatible with "manylinux" wheels, used by numpy >= 1.11
  - pip install flake8
  - pip install --editable .[test]
script: ./travis-run-tests.sh
before_deploy:
  - openssl aes-256-cbc -K $encrypted_5636fd88352f_key -iv $encrypted_5636fd88352f_iv -in openfisca_bot.enc -out openfisca_bot -d
deploy:
  - provider: script
    skip_cleanup: true
    script: ./travis-release-tag.sh
    on:
      branch: master
  - provider: pypi
    user: openfisca-bot
    password:
      secure: AOyunNmfm6Q5pvCLcoE6DwnyINAhAvxguQz82r+AtjSYYq3uv7uKkyX4znEw5g7fa/2fqOzCMZtEWMeiqLRxFlGcbJzfncPwHwiVcMJtGCp/y/L9CwHCAfPVJnLfLIJ4MCBxzYOMfIvv1a0FIXTBo8AEw1i/B7mZfit3D05UaHc=
    distributions: "bdist_wheel"
    on:
      tags: true
