[tool.black]
target-version = [ "py310", "py311", "py312", "py313" ]

[tool.codespell]
ignore-words-list = [
    "THIRDPARTY",
    "ans",
    "constitue",
    "exemple",
    "fonction",
    "impot",
    "treshold",
]
skip = "./venv"
