version: 2
jobs:
  build_python2: &build  # Define a build template that can be re-used for Python 3
    environment:
      CREATE_VENV: "virtualenv"
    docker:
      - image: python:2.7.14

    steps:
      - checkout

      - restore_cache:
          key: v1-{{ .Environment.PY_VERSION }}-{{ checksum "setup.py" }}

      - run:
          name: Create a virtualenv
          command: |
            mkdir -p /tmp/venv/openfisca-core
            ${CREATE_VENV} /tmp/venv/openfisca-core
            echo "source /tmp/venv/openfisca-core/bin/activate" >> $BASH_ENV

      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip twine wheel
            pip install --editable .[test] --upgrade
          #  pip install --editable git+https://github.com/openfisca/country-template.git@BRANCH_NAME#egg=OpenFisca-Country-Template  # use a specific branch of OpenFisca-Country-Template

      - save_cache:
          key: v1-{{ .Environment.PY_VERSION }}-{{ checksum "setup.py" }}
          paths:
            - .
            - /tmp/venv/openfisca-core

      - run:
          name: Run tests
          command: make test

      - run:
          name: Check version number has been properly updated
          command: |
            git fetch
            ./.circleci/check-version-bump.sh

  build_python3:
    <<: *build  # Use the build template defined above
    docker:
      - image: python:3.6
    environment:
      CREATE_VENV: "python -m venv"

  deploy_python2: &deploy  # Define a deploy template that can be re-used for Python 3
    docker:
      - image: python:2.7.14
    environment:
      PYPI_USERNAME: openfisca-bot
      # PYPI_PASSWORD: this value is set in CircleCI's web interface; do not set it here, it is a secret!

    steps:
      - checkout

      - restore_cache:
          key: v1-{{ .Environment.PY_VERSION }}-{{ checksum "setup.py" }}

      - run:
          name: Upload a Python 2 package to Pypi and publish a tag if functional changes were made
          command: |
            source /tmp/venv/openfisca-core/bin/activate
            ./.circleci/deploy-python-$PY_VERSION.sh

  deploy_python3:
    <<: *deploy  # Use the deploy template defined above
    docker:
      - image: python:3.6

workflows:
  version: 2
  openfisca-core:
    jobs:
      - build_python2:
          context: Py2  # Creates the PY_VERSION environment variable.
      - build_python3:
          context: Py3  # Creates the PY_VERSION environment variable.
      - deploy:
          requires:  # Only deploy if tests passed both with Python 2 and Python 3
            - build_python2
            - build_python3
          filters:
            branches:
              only: master
      - deploy_python3:  # Only deploy if tests passed both with Python 2 and Python 3
          requires:
            - build_python2
            - build_python3
          filters:
            branches:
              only: master
