version: 2
jobs:
  build_python2:
    docker:
      - image: python:2.7.14

    steps:
      - checkout

      - restore_cache:
          key: v1-py2-{{ checksum "setup.py" }}

      - run:
          name: Create a virtualenv
          command: |
            mkdir -p /tmp/venv/openfisca-core
            virtualenv /tmp/venv/openfisca-core
            echo "source /tmp/venv/openfisca-core/bin/activate" >> $BASH_ENV

      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip twine wheel
            pip install --editable .[test] --upgrade
          #  pip install --editable git+https://github.com/openfisca/country-template.git@BRANCH_NAME#egg=OpenFisca-Country-Template  # use a specific branch of OpenFisca-Country-Template

      - save_cache:
          key: v1-py2-{{ checksum "setup.py" }}
          paths:
            - /tmp/venv/openfisca-core

      - run:
          name: Run tests
          command: make test

      - run:
          name: Check version number has been properly updated
          command: |
            git fetch
            ./.circleci/check-version-bump.sh

  deploy_python2:
    docker:
      - image: python:2.7.14
    environment:
      PYPI_USERNAME: openfisca-bot
      # PYPI_PASSWORD: this value is set in CircleCI's web interface; do not set it here, it is a secret!

    steps:
      - checkout

      - restore_cache:
          key: v1-py2-{{ checksum "setup.py" }}

      - run:
          name: Upload a Python 2 package to Pypi and publish a tag if functional changes were made
          command: |
            source /tmp/venv/openfisca-core/bin/activate
            ./.circleci/deploy-python-2.sh

  build_python3:
    docker:
      - image: python:3.6

    steps:
      - checkout

      - restore_cache:
          key: v1-py2-{{ checksum "setup.py" }}

      - run:
          name: Create a virtualenv
          command: |
            mkdir -p /tmp/venv/openfisca-core
            python -m venv /tmp/venv/openfisca-core
            echo "source /tmp/venv/openfisca-core/bin/activate" >> $BASH_ENV

      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip twine wheel
            pip install --editable .[test] --upgrade
          #  pip install --editable git+https://github.com/openfisca/country-template.git@BRANCH_NAME#egg=OpenFisca-Country-Template  # use a specific branch of OpenFisca-Country-Template

      - save_cache:
          key: v1-py3-{{ checksum "setup.py" }}
          paths:
            - .
            - /tmp/venv/openfisca-core

      - run:
          name: Run tests
          command: make test

      - run:
          name: Check version number has been properly updated
          command: |
            git fetch
            ./.circleci/check-version-bump.sh

  deploy_python3:
    docker:
      - image: python:3.6
    environment:
      PYPI_USERNAME: openfisca-bot
      # PYPI_PASSWORD: this value is set in CircleCI's web interface; do not set it here, it is a secret!

    steps:
      - checkout

      - restore_cache:
          key: v1-py3-{{ checksum "setup.py" }}

      - run:
          name: Upload a Python 3 package to Pypi
          command: |
            source /tmp/venv/openfisca-core/bin/activate
            ./.circleci/deploy-python-3.sh

workflows:
  version: 2
  openfisca-core:
    jobs:
      - build_python2
      - build_python3
      - deploy_python2:
          requires:  # Only deploy if tests passed both with Python 2 and Python 3
            - build_python2
            - build_python3
          filters:
            branches:
              only: fixup-py3
      - deploy_python3:  # Only deploy if tests passed both with Python 2 and Python 3
          requires:
            - build_python2
            - build_python3
          filters:
            branches:
              only: fixup-py3
