name: Test package

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

      numpy:
        required: true
        type: string

      python:
        required: true
        type: string

      activate_command:
        required: true
        type: string

jobs:
  test:
    runs-on: ${{ inputs.os }}
    name: test-core-${{ inputs.os }}-np${{ inputs.numpy }}-py${{ inputs.python }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TERM: xterm-256color  # To colorize output of make tasks.

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python }}

    - name: Use zstd for faster cache restore (windows)
      if: ${{ startsWith(inputs.os, 'windows') }}
      shell: cmd
      run: echo C:\Program Files\Git\usr\bin>>"%GITHUB_PATH%"

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: venv
        key: deps-${{ inputs.os }}-np${{ inputs.numpy }}-py${{ inputs.python }}-${{ hashFiles('setup.py') }}

    - name: Cache build
      uses: actions/cache@v4
      with:
        path: venv/**/[Oo]pen[Ff]isca*
        key: build-${{ inputs.os }}-np${{ inputs.numpy }}-py${{ inputs.python }}-${{ hashFiles('setup.py') }}-${{ github.sha }}

    - name: Run Openfisca Core tests
      run: |
        ${{ inputs.activate_command }}
        make test-core
        python -m coveralls --service=github

    - name: Run Country Template tests
      if: ${{ startsWith(inputs.os, 'ubuntu') }}
      run: |
        ${{ inputs.activate_command }}
        make test-country

    - name: Run Extension Template tests
      if: ${{ startsWith(inputs.os, 'ubuntu') }}
      run: |
        ${{ inputs.activate_command }}
        make test-extension
